const complimentBtn = document.getElementById("compliment-btn");
const btnLabel = document.getElementById("btnLabel");

// to be added with more //
const compliments = [
  "The little like freckles, you know what i mean that are on your face. It makes you unique and so beautiful.",
  "Your lips are perfectly shaped, every kiss feels just right.",
  "Your hair is so cute, I love how you can style it differently, be creative with it and still look stunning in every hairstyle. (you know I don't have a favorite anymore HAHAHHA)",
  "Your smile, whether it’s with your dimples or with your teeth, it brings me so much joy to see you smile whether it's cause of me or not.",
  "The way you stand up yung pag all your weight is in just one foot, so para kang naka tilt. It's just so you.",
  "Your fashion sense, you always know what works for you. You know what looks good on you, you know your style and you're beautifu everytime no matter what you wear.",
  "Your laugh, it's honestly a blessing to make you laugh and when you do lalo na yung tawang tawa ka it's so contagious you have no idea. You look so happy and just enjoying. I love it.",
  "Your mean jokes and teasing are secretly my favorite. I know that I've been sungit most of the time when you tease me and joke but it's not you without it and I love it. I'd honestly think you would've gone to a long ass semenary if you never teased me again. Don't ever stop please.",
  "I love your love for food like me (fatasses for life 😝). I love how we love eating and just trying new things and eating a lot. I love that you're not shy about it and you're comfortable to act like that with me.",
  "Eating with you is one of my favorite things to do. Let's eat and watch all the time. Food is something we should never limit our money and time on.",
  "You’re the kindest person I know. I love how kind hearted you are. You may not look like it at first glance but you're the nicest person i know and i don’t mean that in a yung naka ngiti, soft spoken type shi HELL NAH not that, you should only be like that to me okay but joking aside, you're honestly the kindest person i know you have such a kind heart, you don't see things as black and white but you know your morals, you know what’s tolerable for you and what’s unforgivable.",
  "You're loyal as hell, i basta d mo ka gagaguhin and no one crosses a line with you, you're in my corner, you will defend you and be by my side through it all.",
  "Next is your patience and understanding, those two things are something I really admire and even get jealous of because I want to have them too. Words can’t even describe how important these two traits are, and it’s insane to me how you have both with no holes, js purity.",
  "I love how pure you are, so clear, and when you love, you give it your all no matter what. Your intentions are pure and buong puso, and it’s honestly so scary how you’re able to give your all, but you do, and that’s what I love about you.",
  "I love how when you sleep, you always have something in any sleeping position. 1 when naka fold elbows mo, eeither like naka position above the head or below the chin if that makes sense. 2  dapat may naka ipit somewhere, you have to have a certain body part like nakasuksok sa isang area sa bed. 3 i love how you need a yakap kung hindi present yung first 2, you'll have a cold pillow to tuck between your legs and arms.",
  "I love how your eyes look when they're barely existent, it means your smiling.",
  "The lines on your face, I know you hate them but hey make you so unique and I truly believe that they contribute to your beauty.",
  "Your armpit, yes your armpit deserves a compliment because I just love it. I love smelling it kahit mabaho and I love looking at it",
  "I love how you get really into the series that you watch. I remember before you wldnt reply to me for a while because you’d be so into what you were watching. Sa series palang grabe na yung attention what more to your significant other.",
  "I love how much you love sushi and japanese food. I’m pretty sure I’ve eaten at more japanese restos in our 1 year and a half relationship than my whole life for as far as I can remember.",
  "I love how open minded you are, I’ve said how you don’t see things as black and white but still have your morals shows how open minded you are as a person, you accept but you know what shldnt be.",
  "You’re the most trustworthy and reliable person. You never left me, you were always there for me, and you listened to me so much. Your patience is through the roof with all the shit gaano ka babaw na sinasabi ko sayo.",
  "Your acceptance of me, you accepted my past, you accepted just how I am, you push out the best in me but you still accept the stuff that js makes me me.",
  "I love when you always encourage me especially when I’m down. You always know just what to say and I’m really grateful that I know I’ll feel better when I talk to you.",
  "I love your IDGAF attitude, no matter what you know who you are, you don’t take the bullshit people say and you mind your own business.",
  "I love how strong you are, I love that despite everything you’ve gone through you got through it without compromising how beautiful of a human being you are.",
  "You’re amount of love towards your cousins, you really cherish the time you have with them and lalo na sa mga younger, there may be an age gap but you make sure you don’t make that evident, and i really admire that about you.",
  "I love how much you love the beach and js swimming in general, just being under the sun, getting a tan, and just enjoying, it’s your peace.",
  "I really appreciate your support in my cooking. May mga times na sobrang alat yung nagawa ko and you still said it was good, you didn’t lie, you still said it was salty but you never brought me down for cooking a meal that was almost inedible.",
  "I really really love your clinginess, please don’t ever stop. I love it when you hug me, when you kiss me, when you want us touching and being close to each other.",
  "I may show annoyance sometimes but I love it when you use me, when you like utos me. I’m not able to do a lot of things for you all the time so just those things you know I wld never say no kahit ano man ipakita ko.",
  "I love how we can be authentic when towards each other, no fake. We can be weird and everything and we’d still love each other.",
  "I love it when you get shy, it’s really cute to see that you’re still shy. You care abt how you look and what you do and it’s admiring and cute. On top of that when you smile and hide your face it’s just so uplifting and it brings me so much joy.",
  "I love that despite your worries and not super eager to join me and my family you still do. You know it’d make me happy and you do it.",
  "I’m really grateful that you’ve been open to your family about me. I’m really happy na despite you still figuring things out you’re open about me and you love us.",
  "I know I say all the time that you shld always drink water and lessen your sweets but I really find it cute how much you love eating sweets and how your mood just gets better when you eat.",
  "It's really cool how you've basically adapted some of the stuff I say, like since we talk every single day you've just had it engraved in your mind.",
  "I really appreciate yung pagasikaso mo saakin, yung you always make sure I look presentable and not kawawa. You always look out for me in that way.",
  "I love how arte you are, may mga moments talaga na may pagkaarte ka and it give personality, yes syempre masasabi ko naman na d ka maarte na like yung mga nakakainis, pero yung arte mo it's just cute and silly.",
  "I love your goofy self, yung mga times lang na you really let out lose and just be silly.",
  "I really appreciate how much you've taught me, you've really pushed me to be a better person, and so much more. I'm really determined to make you as happy as you make me.",
  "I love your view of life, how you see it and you know what's important and what we shouldn't feel so bad about",
  "I'm really grateful on your acceptance with our stuffed toys, and you treat them really like our children, I know I can't give you real children and I'll forever really hate that fact, but I know I can give you if not better as good as that.",
  "I want you to know how much you've changed my perspective, how you've changed how I act and think. You've really put me in my place.",
  "I really appreciate that hindi ka maarte in terms of like that we commute, eat at cheap places, I love that all you care about is being together",
  "I love your protectiveness of me, kahit mukha akong lalaki you still treat me like a girl, you still make sure that I don't js get bullied around or get told mean stuff at. You always encourage me to stand for myself.",
  "I really appreciate your worry of me, you always think about me and how I feel. No more no less. That's it and that's true. And I really am super grateful for it.",
  "I love it when you touch me, I love when you kiss my cheek it shows me that you love me, I love when you hug my waist it shows me that you want me, I love when you scratch or rub my batok it shows that you're there for me, and I love when you hold my arm it shows me you feel safe with me.",
  "I love your fighting spirit, how competetive you are and how you have this will to fight.",
  "I love your silly trashtalking when we play, naalala ko nung nagccod tayo nagaway pa tayo eh. Hehe i'm sorry for that but I find it silly and cute kahit mas magaling naman ako sayo bleh!",
  "I appreciate na when we take picture you like lean towards the side para I look taller and the overall picture just looks better.",
  "I really appreciate how you taught me to have better manners, you know I didn't grow up with them so you helping me develop that is something I really appreciate. I really love that about you.",
  "Another thing I really love and cherish is our naps and sleeping together, it's so peaceful and just something you want to happen forever.",
  "Another thing I cherish is watching with you, it's really our bonding time together, our go to, our classic. And I really appreciate all the times we've watched and will continue to cherish our movie watching.",
  "I love your honesty, kahit alam mong hindi siya like makakasaya you still remain honest. And it's one of the things I really admire about you.",
  "I appreciate na hanggaang ngayon di ka pagnagsasawa saakin, you're still here and I know you love me a lot. And I'm really grateful and lucky to have someone like you.",
  "I find your thingy about your boobs so silly, but I support you and I will love you wholeheartedly.",
  "I really am thankful as well that you deal with my overthinkness kahit gaano kababaw siya, you listend and you reassure.",
  "I love the moments where we're js seated and basically judge people. It's not amazing for them HDABHDAHD but it really bonds us together and makes us laugh.",
  "I love how you give me opportunities to help you, like learn how to do girly stuff so I can help you, you also let me remove your contacts and you tolerate my awful massage skills and js hope I get better at that.",
  "I just love how much you know me. That's it you know what it means and it's really amazing you just know. I want to be able to repay that to you throughout our relatiomship.",
  "I love that you think about me, yes the way you think about my feelings and put me first but not only that but before when you hugged my hoodie when you miss me, and also when you think of us cuddling when you sleep. It's cute and I really love it. I'm happy I make you feel that.",
  "I love the moments when we talk about our future, our plans the stuff we'd do together. It gives future and hope in our relationship.",
  "I love that we choose each other. Plain and simple.",
  "I love that we love each other, I love being loved by you and I hope I make you feel the same way too.",
  "I love us Wanika, and I want this to work so badly, I'm getting better and I know that I may not be able to give you biological children, I may not be able to be a husband, and give you a normal life but, I know I can make you happy and give you more than enough that you need."
];

complimentBtn.addEventListener("click", () => {
    let randomNum = Math.floor(Math.random() * compliments.length);
    btnLabel.textContent = compliments[randomNum];
});
